In [3]:
import pandas as pd
import numpy as np
import ast
from tqdm import tqdm

In [4]:
df_job = pd.read_excel('./position.xlsx')
df_job.shape

(1575, 17)

In [30]:
df_per = pd.read_excel('./user.xlsx')
df_per.shape

(10877, 23)

In [5]:
df_job.head()

,序号,招聘信息 ID,企业名称,招聘岗位,学历要求,经验要求,岗位关键词,性质,岗位需求量,最大薪资,最小薪资,企业工作地点,公司类型,行业,公司规模,职位描述,职位福利
0,1,1648527394191049984,众云网,售前技术支持,大专,不限,"[{'id': '1648528107189178368', 'createTime': '...",全职,6,20000,12000,深圳市南山区粤海街道滨海社区海天一路19、17、18号软件产业基地4栋511,民营公司,"['互联网', '计算机软件']",150-500人,岗位职责：\n1、负责配合客户及项目需要，完成技术交流，提供解决方案；\n2、负责网络安全、...,"['餐饮补贴', '专业培训', '弹性工作']"
1,2,1648527394191049984,众云网,数据安全高级经理,大专,不限,"[{'id': '1648528387356102656', 'createTime': '...",全职,10,26000,16000,深圳市南山区粤海街道滨海社区海天一路19、17、18号软件产业基地4栋511,民营公司,"['互联网', '计算机软件']",150-500人,主要职责：\n1、辅助集团数据安全规划工作，梳理摸底调研思路并定位现状和需求，设计可落地解决...,"['餐饮补贴', '专业培训', '弹性工作']"
2,3,1648527394191049984,众云网,数据安全项目经理,大专,不限,"[{'id': '1648528629572964352', 'createTime': '...",全职,100,25000,15000,深圳市南山区粤海街道滨海社区海天一路19、17、18号软件产业基地4栋511,民营公司,"['互联网', '计算机软件']",150-500人,主要职责：\n1、负责集团内数据安全项目的推广工作，按照部门数据安全建设规划，与集团内客户开...,"['餐饮补贴', '专业培训', '弹性工作']"
3,4,1648165203084440064,森羽网络,数据挖掘工程师,大专,不限,"[{'id': '1648168464491352064', 'createTime': '...",全职,5,8000,5000,山东省济宁市高新区洸河街道百丰大厦803,民营公司,['互联网'],50-100人,1、全日制本科及以上学历，计算机、数学、统计等相关 专业：超过三年的相关工作经验：\n2、熟...,"['餐饮补贴', '专业培训', '弹性工作']"
4,5,1648165203084440064,森羽网络,数据管理,大专,不限,"[{'id': '1648165203084447745', 'createTime': '...",全职,6,6000,3500,山东省济宁市高新区洸河街道百丰大厦803,民营公司,['互联网'],50-100人,主要工作职责：\n1.完成业务数据库以及部分核心数据的维护工作，包括各项数据的采集、处理汇总...,"['餐饮补贴', '专业培训', '弹性工作']"

In [23]:
行业统计 = {}

In [24]:
for i in range(len(df_job)):
  hy_txt = df_job.loc[i,'行业']
  hy_list = ast.literal_eval(hy_txt)
  for hy in hy_list:
    if hy in 行业统计:
      行业统计[hy] += 1
    else:
      行业统计[hy] = 1

In [28]:
s = pd.Series(行业统计).sort_values(ascending=False)
s.to_excel('./行业统计.xlsx')

In [29]:
s

互联网       1555
电子商务       150
软件          67
大数据         48
数据服务        33
电商          32
通信设备        15
智能硬件        14
计算机软件       12
金融          11
计算机          6
医疗           5
游戏           5
物流           4
通信           3
家电           3
教育           3
服饰           3
制造           3
通讯           3
企业服务         2
人力资源服务       2
机械           2
水利           2
地产           2
家居           2
电子信息         2
环境           1
不限           1
计量           1
广告           1
在线教育         1
生活服务         1
医疗健康         1
dtype: int64

In [31]:
df_per.head()

,序号,求职者 ID,姓名,预期岗位,工作地区,经验,性别,生日,政治面貌,自我评价,...,工作性质,简历关键词,工作经历,项目经历,竞赛经历,教育经历,培训经历,证书,语言,技能
0,1,1648621861036219904,张女士,"[""数据分析师""]","[""广东省"",""广州市"",""天河区""]",无经验,女,2002-12-18T16:00:00.000Z,LEAGUE_MEMBER,本科毕业，具有多年的比赛经验，曾获数据挖掘一等奖，数据分析一等奖，数学竞赛二等奖，数学建模一...,...,实习,[],[],[],[],[],[],[],[],[]
1,2,1648621300526210048,蔡先生,"[""计算机视觉工程师""]","[""北京市"",""北京市"",""东城区""]",4年工作经验,男,2018-04-09T16:00:00.000Z,PROBATIONARY_PARTY_MEMBER,法律改革,...,全职,[],[],[],[],[],[],[],[],[]
2,3,1648345891960120064,蔡女士,"[""其他""]","[""山东省"",""菏泽市"",""曹县""]",6年工作经验,女,2023-04-17T16:00:00.000Z,PARTY_MEMBER,再看一眼就会爆炸,...,全职,[],[],[],[],[],[],[],[],[]
3,4,1648221000086710016,特先生,"[""图像处理工程师"",""自然语言处理工程师""]","[""天津市"",""天津市"",""河东区""]",1年工作经验,男,2023-04-03T16:00:00.000Z,LEAGUE_MEMBER,awdaw,...,全职,[],[],[],[],[],[],[],[],[]
4,5,1647944223779059968,傻女士,"[""数据挖掘工程师"",""算法工程师"",""自然语言处理工程师""]","[""天津市"",""天津市"",""河东区""]",5年工作经验,女,1999-03-31T16:00:00.000Z,PARTY_MEMBER,我TM就是一个傻杯,...,全职,[],[],[],[],[],[],[],[],[]

In [37]:
岗位统计 = {}

In [38]:
for i in range(len(df_per)):
  hy_txt = df_per.loc[i,'预期岗位']
  hy_list = ast.literal_eval(hy_txt)
  for hy in hy_list:
    if hy in 岗位统计:
      岗位统计[hy] += 1
    else:
      岗位统计[hy] = 1

In [39]:
岗位统计

{'数据分析师': 10802,
 '计算机视觉工程师': 5,
 '其他': 44,
 '图像处理工程师': 12,
 '自然语言处理工程师': 19,
 '数据挖掘工程师': 10739,
 '算法工程师': 14,
 '机器学习工程师': 26,
 'Hadoop大数据开发工程师': 59,
 '"': 14,
 '\\': 26,
 '[': 2,
 '数': 3,
 '据': 3,
 '分': 2,
 '析': 2,
 '师': 3,
 ']': 2,
 ',': 1,
 '挖': 1,
 '掘': 1,
 '工': 1,
 '程': 1}

In [42]:
s1 = pd.Series(岗位统计).sort_values(ascending=False)
s1.to_excel('./岗位统计.xlsx')